pool:
  name: self-hosted

trigger: none

pr:
  - master

variables:
  dotnetVersion: net8.0

steps:
  - checkout: self
    fetchDepth: 0
  
  - task: UseDotNet@2
    inputs:
      version: 8.0.x

  - task: CmdLine@2
    inputs:
      script: '/home/david/.dotnet/tools/nbgv cloud'

  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: '6.x'

  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
  
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.sln'
  