# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

resources:
  - repo: self

variables:
  dotnetVersion: 'net7.0'
  dockerId: davidxchen
  imageName: tictactoe

stages:
- stage: Build
  displayName: Build image
  jobs:
    - job: Build
      displayName: Build
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: CmdLine@2
          inputs:
            script: 'nbgv cloud'

        - powershell: |
            $version = nbgv get-version -f json | ConvertFrom-Json
            
            Write-Host $version.SemVer2
            Write-Host $version.NuGetPackageVersion
            
            [string] $SemVer2= $version.SemVer2
            Write-Host "Setting the version of the build to '$SemVer2'."
            Write-Host "##vso[task.setvariable variable=prereleaseVersionNumber]$SemVer2"

          displayName: 'PowerShell Script'

        - task: Docker@2
          displayName: Build an image
          inputs:
            command: build
            dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
            tags: |
              $(prereleaseVersionNumber)
              latest
            arguments: '--build-arg APP_VER=$(prereleaseVersionNumber) NET_VER=$(dotnetVersion)'