pool:
  name: Mac-Agent

trigger:
  - master
pr:
  - master

variables:
  dotnetVersion: net7.0
  dockerId: davidxchen
  dockerRepo: tictactoe
  imageName: davidxchen/tictactoe

steps:
  - checkout: self
    fetchDepth: 0

  - task: CmdLine@2
    inputs:
      script: 'nbgv cloud'

  - powershell: |
      $version = nbgv get-version -f json | ConvertFrom-Json
      
      Write-Host $version.SemVer2
      Write-Host $version.NuGetPackageVersion
      
      [string] $SemVer2= $version.SemVer2
      Write-Host "Setting the version of the build to '$SemVer2'."
      Write-Host "##vso[task.setvariable variable=prereleaseVersionNumber]$SemVer2"

    displayName: 'PowerShell Script'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        colima start
        docker buildx build -f $(Build.SourcesDirectory)/Dockerfile \
          --platform linux/amd64 \
          --build-arg APP_VER=$(prereleaseVersionNumber) --build-arg NET_VER=$(dotnetVersion) \
          -t $(imageName):v$(prereleaseVersionNumber) -t $(imageName):latest .

  - task: Docker@2
    inputs:
      containerRegistry: '$(dockerId)'
      repository: '$(dockerRepo)'
      command: 'push'
      arguments: '-t $(imageName):v$(prereleaseVersionNumber) -t $(imageName):latest'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        colima stop