pool:
  name: self-hosted

trigger: none

pr:
  - master

variables:
  dotnetVersion: net8.0

steps:
  - checkout: self
    fetchDepth: 0
  
  - task: UseDotNet@2
    inputs:
      version: 8.0.x

  - task: CmdLine@2
    inputs:
      script: '/home/david/.dotnet/tools/nbgv cloud'

  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: '6.x'

  - task: NuGetCommand@2
    inputs:
      command: restore
      restoreSolution: '**/*.sln'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/src/TicTacToe/TicTacToe.csproj'
  
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
  
  - script: |
      npm install
      npm run build
    workingDirectory: '$(Build.Repository.LocalPath)/src/tictactor-web/'