pool:
  name: self-hosted

trigger:
  - master
pr:
  - master

variables:
  dotnetVersion: net8.0
  dockerId: davidxchen
  dockerRepo: tictactoe
  imageName: davidxchen/tictactoe

steps:
  - checkout: self
    fetchDepth: 0

  - task: CmdLine@2
    inputs:
      script: '/home/david/.dotnet/tools/nbgv cloud'

  - task: CmdLine@2
    inputs:
      script: 'echo $(Build.BuildNumber)'

  - powershell: |
      $version = /home/david/.dotnet/tools/nbgv get-version -f json | ConvertFrom-Json
      
      Write-Host $version.SemVer2
      Write-Host $version.NuGetPackageVersion
      
      [string] $SemVer2= $version.SemVer2
      Write-Host "Setting the version of the build to '$SemVer2'."
      Write-Host "##vso[task.setvariable variable=prereleaseVersionNumber]$SemVer2"

    displayName: 'PowerShell Script'

  - task: DownloadSecureFile@1
    name: prodDocker
    inputs:
      secureFile: 'pass.txt'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        colima start
        cat $(prodDocker.secureFilePath) | docker login -u $(dockerId) --password-stdin
        docker buildx build --file $(Build.SourcesDirectory)/Dockerfile \
          --platform linux/amd64 \
          --build-arg APP_VER=$(prereleaseVersionNumber) --build-arg NET_VER=$(dotnetVersion) \
          -t $(imageName):v$(prereleaseVersionNumber) -t $(imageName):latest \
          --push .
        docker logout
        colima stop